language: node_js

install: npm install

jobs:
  include:
    - stage: test 👩🏽‍💻
      script: npm run test-travis
      node_js: lts/*
    - node_js: node

    - stage: lint ✨
      script: npm run lint
      node_js: lts/*

cache:
  directories:
    - node_modules

git:
  depth: 3
